-- Libro Mayor — datos semilla del catálogo
-- Generado a partir de DEFAULT_CATALOG en itam-cp-estudio.html.
-- Corre esto DESPUÉS de supabase/schema.sql, en el SQL editor de tu proyecto.

insert into public.subjects (id, code, division, sort_order) values
  ('proc', 'Proceso Contable', 'Negocios', 0),
  ('cp1', 'Contabilidad Financiera I', 'Negocios', 1),
  ('cp2', 'Contabilidad Financiera II', 'Negocios', 2),
  ('fin1', 'Finanzas en los Negocios I', 'Negocios', 3),
  ('cost', 'Administración Estratégica de Costos', 'Negocios', 4),
  ('aud', 'Auditoría Analítica', 'Negocios', 5),
  ('anfin', 'Análisis Financiero de la Empresa', 'Negocios', 6),
  ('combneg', 'Combinación de Negocios', 'Negocios', 7),
  ('costos', 'Contabilidad de Costos', 'Negocios', 8),
  ('costdec', 'Costos para la Toma de Decisiones', 'Negocios', 9),
  ('contintl', 'Contabilidad Internacional (IFRS)', 'Negocios', 10),
  ('instfin', 'Contabilización y Valuación de Instrumentos Financieros', 'Negocios', 11),
  ('contraloria', 'Control Interno y Prevención de Fraudes', 'Negocios', 12),
  ('imp1', 'Impuestos Corporativos I', 'Negocios', 13),
  ('imp2', 'Estrategias Fiscales Corporativas', 'Negocios', 14),
  ('impfis', 'Estrategias Fiscales Patrimoniales', 'Negocios', 15),
  ('neg1', 'Estrategia de Negocios I', 'Negocios', 16),
  ('tray1', 'Trayectorias en Contaduría: Propósito y Programa', 'Negocios', 17),
  ('intro', 'Introducción a la Contaduría Analítica', 'Negocios', 18),
  ('fin2', 'Finanzas en los Negocios II', 'Negocios', 19),
  ('integrada', 'Contaduría Analítica Integrada', 'Negocios', 20),
  ('corporativa', 'Contaduría Analítica Corporativa', 'Negocios', 21),
  ('tray2', 'Trayectorias en Negocios II: Equipo y Liderazgo', 'Negocios', 22),
  ('tray3', 'Trayectorias en Negocios III: Emprendimiento e Impacto', 'Negocios', 23),
  ('esg', 'Reportes Corporativos de Sostenibilidad ESG', 'Negocios', 24),
  ('riesgos', 'Administración y Control de Riesgos', 'Negocios', 25),
  ('fiscalint', 'Estrategias Fiscales Internacionales', 'Negocios', 26),
  ('ecogerencial', 'Economía Gerencial', 'Negocios', 27),
  ('calc', 'Cálculo Aplicado', 'Ciencias Exactas', 28),
  ('algebra', 'Álgebra Lineal Aplicada', 'Ciencias Exactas', 29),
  ('est1', 'Estadística I', 'Ciencias Exactas', 30),
  ('est2', 'Estadística II', 'Ciencias Exactas', 31),
  ('pronosticos', 'Métodos de Pronósticos', 'Ciencias Exactas', 32),
  ('introderecho', 'Introducción al Derecho Corporativo', 'Derecho', 33),
  ('derechocorp', 'Derecho Empresarial', 'Derecho', 34),
  ('derfiscal1', 'Derecho Fiscal I', 'Derecho', 35),
  ('derlaboral', 'Derecho Laboral I', 'Derecho', 36);

insert into public.topics (id, subject_id, title, sort_order) values
  ('pc1', 'proc', 'Un marco para la contabilidad financiera', 0),
  ('pc2', 'proc', 'El ciclo contable: durante el período', 1),
  ('pc3', 'proc', 'El ciclo contable: fin del período', 2),
  ('pc4', 'proc', 'Efectivo y controles internos', 3),
  ('pc5', 'proc', 'Cobrables y ventas', 4),
  ('pc6', 'proc', 'Inventario y costo de ventas', 5),
  ('pc7', 'proc', 'Activos no circulantes', 6),
  ('pc8', 'proc', 'Pasivos de corto y largo plazo', 7),
  ('pc9', 'proc', 'Capital contable', 8),
  ('pc10', 'proc', 'Estado de flujos de efectivo', 9),
  ('pc11', 'proc', 'Análisis de estados financieros', 10),
  ('c11', 'cp1', 'Entorno y marco conceptual de la contabilidad financiera', 0),
  ('c12', 'cp1', 'Proceso contable: registro, libro mayor y ajustes', 1),
  ('c13', 'cp1', 'Estado de Situación Financiera y Estado de Resultado Integral', 2),
  ('c14', 'cp1', 'Reconocimiento de ingresos (5 pasos)', 3),
  ('c15', 'cp1', 'Valor del dinero en el tiempo', 4),
  ('c16', 'cp1', 'Efectivo y cuentas por cobrar', 5),
  ('c17', 'cp1', 'Inventarios: valuación y consideraciones adicionales', 6),
  ('c18', 'cp1', 'Propiedades, planta y equipo, e intangibles', 7),
  ('c21', 'cp2', 'Pasivos de corto plazo y contingencias', 0),
  ('c22', 'cp2', 'Bonos y documentos a largo plazo', 1),
  ('c23', 'cp2', 'Arrendamientos', 2),
  ('c24', 'cp2', 'Impuestos a la utilidad', 3),
  ('c25', 'cp2', 'Pensiones y beneficios post-empleo', 4),
  ('c26', 'cp2', 'Capital contable', 5),
  ('c27', 'cp2', 'Compensaciones basadas en acciones y UPA', 6),
  ('c28', 'cp2', 'Cambios contables y corrección de errores', 7),
  ('c29', 'cp2', 'Estado de flujos de efectivo', 8),
  ('f1', 'fin1', 'Introducción a las finanzas: finanzas corporativas y mercados financieros', 0),
  ('f2', 'fin1', 'Matemáticas financieras: valor del dinero en el tiempo, tasas de interés', 1),
  ('f3', 'fin1', 'Anualidades, perpetuidades y tablas de amortización', 2),
  ('f4', 'fin1', 'Valuación de bonos: precio y medidas de rendimiento', 3),
  ('f5', 'fin1', 'Valuación de acciones: modelo de dividendos descontados y VPNOC', 4),
  ('f6', 'fin1', 'Reglas de decisión de inversión: VPN, TIR, periodo de recuperación, índice de rentabilidad', 5),
  ('f7', 'fin1', 'Valuación de empresas y proyectos: estados financieros proforma y flujo de efectivo libre', 6),
  ('f8', 'fin1', 'Costo Promedio Ponderado de Capital (CPPC / WACC)', 7),
  ('co1', 'cost', 'Evolución de la profesión contable y la contabilidad gerencial', 0),
  ('co2', 'cost', 'Costeo y administración basados en actividades (ABC/ABM)', 1),
  ('co3', 'cost', 'Toma de decisiones de optimización: órdenes especiales, producir o comprar, mezcla óptima', 2),
  ('co4', 'cost', 'Teoría de restricciones, ciclo de vida del producto y target costing', 3),
  ('co5', 'cost', 'Administración por excepción, centros de responsabilidad y precios de transferencia', 4),
  ('au1', 'aud', 'Ética profesional e independencia', 0),
  ('au2', 'aud', 'Evidencia de auditoría y documentación', 1),
  ('au3', 'aud', 'Muestreo en auditoría', 2),
  ('au4', 'aud', 'Auditoría operacional', 3),
  ('au5', 'aud', 'Audit Data Analytics', 4),
  ('au6', 'aud', 'Reportes de auditoría y expresión de opinión', 5),
  ('au7', 'aud', 'Servicios adicionales de asesoría', 6),
  ('af1', 'anfin', 'Métricas y razones financieras, análisis horizontal y vertical', 0),
  ('af2', 'anfin', 'Mercados globales y locales, valuación relativa por múltiplos', 1),
  ('af3', 'anfin', 'Análisis de apalancamiento y estructura de capital', 2),
  ('af4', 'anfin', 'Análisis de actividades de operación (ciclo neto, EBITDA)', 3),
  ('af5', 'anfin', 'Análisis de actividades de inversión e intangibles', 4),
  ('af6', 'anfin', 'Análisis de rentabilidad (Dupont, EV)', 5),
  ('af7', 'anfin', 'Análisis de flujo de efectivo', 6),
  ('af8', 'anfin', 'Análisis prospectivo y valuación por DCF', 7),
  ('cn1', 'combneg', 'Inversiones en instrumentos de capital y deuda', 0),
  ('cn2', 'combneg', 'Adquisiciones de negocios y tipos de combinación', 1),
  ('cn3', 'combneg', 'Consolidación: crédito mercantil y estados financieros consolidados', 2),
  ('cn4', 'combneg', 'Conversión de estados financieros a moneda extranjera', 3),
  ('cn5', 'combneg', 'Efectos de la inflación y reexpresión', 4),
  ('cs1', 'costos', 'Introducción a la contabilidad de costos', 0),
  ('cs2', 'costos', 'Contabilización de materia prima', 1),
  ('cs3', 'costos', 'Contabilización de mano de obra', 2),
  ('cs4', 'costos', 'Ciclo de la contabilidad de costos (órdenes y GIF)', 3),
  ('cs5', 'costos', 'Sistema de acumulación de costos por procesos (PEPS/UEPS/Promedio)', 4),
  ('cs6', 'costos', 'Sistemas híbridos, JIT y costeo back-flush', 5),
  ('cs7', 'costos', 'Introducción al costeo ABC', 6),
  ('cs8', 'costos', 'Gastos indirectos de fabricación y prorrateos', 7),
  ('cs9', 'costos', 'Pérdidas, desperdicio y mercancía defectuosa', 8),
  ('cd1', 'costdec', 'Asignación de costos conjuntos', 0),
  ('cd2', 'costdec', 'Costeo absorbente vs. costeo directo (NIF C-4)', 1),
  ('cd3', 'costdec', 'Comportamiento de costos y estimación (alto-bajo, regresión)', 2),
  ('cd4', 'costdec', 'Modelo Costo-Volumen-Utilidad y punto de equilibrio', 3),
  ('cd5', 'costdec', 'Costeo estándar como herramienta de planeación', 4),
  ('cd6', 'costdec', 'Presupuesto maestro y presupuesto flexible', 5),
  ('cd7', 'costdec', 'Análisis de variaciones en ventas, MPD, MOD y GIF', 6),
  ('ci1', 'contintl', 'Objetivos de las IFRS y comparación con NIF y US GAAP', 0),
  ('ci2', 'contintl', 'Reconocimiento de ingresos (IFRS 15)', 1),
  ('ci3', 'contintl', 'Impuestos a la utilidad (IAS 12, IFRIC 23)', 2),
  ('ci4', 'contintl', 'Arrendamientos (IAS 17 / IFRS 16)', 3),
  ('ci5', 'contintl', 'Primera adopción de IFRS (IFRS 1)', 4),
  ('ci6', 'contintl', 'Temas complejos: beneficios a empleados, tipo de cambio, deterioro', 5),
  ('if1', 'instfin', 'Marco conceptual NIF B-17 (Valor Razonable)', 0),
  ('if2', 'instfin', 'Deterioro de instrumentos financieros por cobrar (NIF C-16)', 1),
  ('if3', 'instfin', 'Provisiones, contingencias y compromisos (NIF C-9)', 2),
  ('if4', 'instfin', 'Instrumentos financieros derivados y coberturas (NIF C-10)', 3),
  ('if5', 'instfin', 'Instrumentos financieros por pagar (NIF C-19)', 4),
  ('if6', 'instfin', 'Instrumentos con características de pasivo y capital (NIF C-11/C-12)', 5),
  ('if7', 'instfin', 'Transferencia y baja de activos financieros (NIF C-14)', 6),
  ('ct1', 'contraloria', 'Control interno: objetivo y marco normativo', 0),
  ('ct2', 'contraloria', 'Estructura del control interno, roles y responsabilidades', 1),
  ('ct3', 'contraloria', 'Ley Sarbanes-Oxley (SOX)', 2),
  ('ct4', 'contraloria', 'Foreign Corrupt Practices Act (FCPA)', 3),
  ('ct5', 'contraloria', 'Materialidad e importancia relativa', 4),
  ('ct6', 'contraloria', 'Segregación de funciones y delegación de autoridad', 5),
  ('ct7', 'contraloria', 'Puntos de control por proceso de negocio', 6),
  ('ct8', 'contraloria', 'Programa de auditoría interna y aspectos de auditoría forense', 7),
  ('i1', 'imp1', 'Marco normativo del ISR y jerarquía de ordenamientos', 0),
  ('i2', 'imp1', 'Disposiciones generales: objeto, sujetos, base y tasa', 1),
  ('i3', 'imp1', 'Ingresos acumulables', 2),
  ('i4', 'imp1', 'Deducciones autorizadas y no deducibles', 3),
  ('i5', 'imp1', 'Deducción de inversiones', 4),
  ('i6', 'imp1', 'Pérdidas fiscales', 5),
  ('i7', 'imp1', 'Intereses, operaciones financieras y ajuste anual por inflación', 6),
  ('i8', 'imp1', 'Conciliación contable-fiscal y pagos provisionales', 7),
  ('i9', 'imp1', 'PTU e ISR diferido', 8),
  ('i21', 'imp2', 'Régimen fiscal de dividendos (CUCA, CUFIN)', 0),
  ('i22', 'imp2', 'Reembolso y reducción de capital', 1),
  ('i23', 'imp2', 'Compraventa de acciones, fusión y escisión', 2),
  ('i24', 'imp2', 'Ley del Impuesto al Valor Agregado (IVA)', 3),
  ('i25', 'imp2', 'Precios de transferencia', 4),
  ('i26', 'imp2', 'Pagos al extranjero y tratados para evitar doble imposición', 5),
  ('pf1', 'impfis', 'Régimen fiscal de personas físicas: disposiciones generales', 0),
  ('pf2', 'impfis', 'Ingresos por salarios (sueldos)', 1),
  ('pf3', 'impfis', 'Actividades empresariales y profesionales, RESICO', 2),
  ('pf4', 'impfis', 'Arrendamiento de inmuebles', 3),
  ('pf5', 'impfis', 'Enajenación y adquisición de bienes', 4),
  ('pf6', 'impfis', 'Intereses, dividendos y premios', 5),
  ('pf7', 'impfis', 'Declaración anual y deducciones personales', 6),
  ('neg1-t1', 'neg1', 'Temario en construcción — próxima actualización', 0),
  ('tray1-t1', 'tray1', 'Temario en construcción — próxima actualización', 0),
  ('intro-t1', 'intro', 'Temario en construcción — próxima actualización', 0),
  ('fin2-t1', 'fin2', 'Temario en construcción — próxima actualización', 0),
  ('integrada-t1', 'integrada', 'Temario en construcción — próxima actualización', 0),
  ('corporativa-t1', 'corporativa', 'Temario en construcción — próxima actualización', 0),
  ('tray2-t1', 'tray2', 'Temario en construcción — próxima actualización', 0),
  ('tray3-t1', 'tray3', 'Temario en construcción — próxima actualización', 0),
  ('esg-t1', 'esg', 'Temario en construcción — próxima actualización', 0),
  ('riesgos-t1', 'riesgos', 'Temario en construcción — próxima actualización', 0),
  ('fiscalint-t1', 'fiscalint', 'Temario en construcción — próxima actualización', 0),
  ('ecogerencial-t1', 'ecogerencial', 'Temario en construcción — próxima actualización', 0),
  ('ca1', 'calc', 'Conceptos preliminares: funciones lineales, cuadráticas, racionales, exponencial y logaritmo', 0),
  ('ca2', 'calc', 'La derivada: límites, continuidad, reglas de derivación y regla de la cadena', 1),
  ('ca3', 'calc', 'Concavidad, tasas relacionadas y optimización', 2),
  ('ca4', 'calc', 'La integral: definida, antiderivada y Teorema Fundamental del Cálculo', 3),
  ('ca5', 'calc', 'Áreas, valor promedio y otras aplicaciones de la integral', 4),
  ('ca6', 'calc', 'Funciones multivariadas: matrices, determinantes y optimización con Lagrange', 5),
  ('al1', 'algebra', 'Sistemas de ecuaciones lineales y eliminación Gaussiana', 0),
  ('al2', 'algebra', 'Geometría vectorial en R2 y R3', 1),
  ('al3', 'algebra', 'Espacios vectoriales, dependencia e independencia lineal, bases y dimensión', 2),
  ('al4', 'algebra', 'Matrices, operaciones e inversa', 3),
  ('al5', 'algebra', 'Determinantes, matriz adjunta y Regla de Cramer', 4),
  ('al6', 'algebra', 'Valores y vectores propios, diagonalización y cadenas de Markov', 5),
  ('al7', 'algebra', 'Programación lineal (tema opcional)', 6),
  ('e11', 'est1', 'Análisis exploratorio de datos: tipos, distribuciones de frecuencia y medidas de centralidad/dispersión', 0),
  ('e12', 'est1', 'Probabilidad: axiomas, probabilidad condicional y Teorema de Bayes', 1),
  ('e13', 'est1', 'Variables aleatorias discretas (Binomial, Poisson, Geométrica) y continuas (Uniforme, Exponencial, Normal)', 2),
  ('e14', 'est1', 'Vectores aleatorios, distribuciones conjuntas y correlación', 3),
  ('e21', 'est2', 'Muestreo: MAS, estratificado, por conglomerados y diseño de encuestas', 0),
  ('e22', 'est2', 'Teorema Central del Límite y distribuciones muestrales', 1),
  ('e23', 'est2', 'Estimación puntual y propiedades de los estimadores', 2),
  ('e24', 'est2', 'Estimación por intervalos de confianza', 3),
  ('e25', 'est2', 'Pruebas de hipótesis paramétricas', 4),
  ('e26', 'est2', 'Modelo de regresión lineal simple', 5),
  ('pr1', 'pronosticos', 'Introducción a los modelos de pronóstico: métodos cualitativos y cuantitativos', 0),
  ('pr2', 'pronosticos', 'Métodos cualitativos: Delphi, lluvia de ideas, panel de expertos, grupos de enfoque', 1),
  ('pr3', 'pronosticos', 'Repaso de probabilidad y estadística aplicado a pronósticos', 2),
  ('pr4', 'pronosticos', 'Regresión lineal simple y supuestos del modelo', 3),
  ('pr5', 'pronosticos', 'Multicolinealidad y heterocedasticidad en regresión', 4),
  ('pr6', 'pronosticos', 'Estacionariedad y autocorrelación en series de tiempo', 5),
  ('pr7', 'pronosticos', 'Estacionalidad: desestacionalización e índices estacionales', 6),
  ('id1', 'introderecho', 'Teoría general del contrato', 0),
  ('id2', 'introderecho', 'Atributos de la persona (nombre, capacidad, domicilio, patrimonio)', 1),
  ('id3', 'introderecho', 'Introducción a las obligaciones y derechos subjetivos', 2),
  ('dc1', 'derechocorp', 'Sistema Financiero Mexicano: ahorradores, intermediarios y deudores', 0),
  ('dc2', 'derechocorp', 'Autoridades financieras: SHCP, Condusef, IPAB, Banxico', 1),
  ('dc3', 'derechocorp', 'Clasificación del derecho público y privado aplicado a lo corporativo', 2),
  ('df1', 'derfiscal1', 'Finanzas públicas: ingresos, gasto y balance presupuestario', 0),
  ('df2', 'derfiscal1', 'Ingresos petroleros, no petroleros y contribuciones', 1),
  ('df3', 'derfiscal1', 'Paquete económico: Ley de Ingresos, Presupuesto de Egresos y Miscelánea Fiscal', 2),
  ('dl1', 'derlaboral', 'Contexto histórico e internacional del derecho laboral en México', 0),
  ('dl2', 'derlaboral', 'Artículo 123 constitucional y el derecho al trabajo', 1),
  ('dl3', 'derlaboral', 'Fuentes del derecho laboral (CPEUM, tratados, LFT, jurisprudencia)', 2);

insert into public.resources (subject_id, label) values
  ('proc', 'Apuntes completos (12 capítulos)'),
  ('proc', 'Diagramas de flujo contable'),
  ('proc', 'Video: registro de ajustes'),
  ('cp1', 'Temario oficial (Spiceland 9a ed.)'),
  ('cp1', 'Ejercicios por tema'),
  ('cp1', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('cp2', 'Temario oficial (Spiceland 9a ed.)'),
  ('cp2', 'Ejercicios por tema'),
  ('cp2', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('fin1', 'Presentación completa del curso (324 diapositivas, Prof. Julieta Guiza)'),
  ('fin1', 'Berk & DeMarzo, Corporate Finance'),
  ('fin1', 'Plantilla Excel guiada'),
  ('fin1', 'Calculadora financiera'),
  ('cost', 'Cost Management: A Strategic Emphasis (Blocher)'),
  ('cost', 'Casos por módulo'),
  ('cost', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('aud', 'Principles of Auditing (Whittington/Pany)'),
  ('aud', 'Caso ético en equipo'),
  ('aud', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('anfin', 'Financial Statement Analysis (Subramanyam)'),
  ('anfin', 'Terminal Bloomberg / Capital IQ'),
  ('anfin', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('combneg', 'Advanced Financial Accounting (Christensen)'),
  ('combneg', 'Trabajo final: caso de combinación'),
  ('combneg', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('costos', 'Cost Management: A Strategic Emphasis (Blocher)'),
  ('costos', 'Tableau para visualización de datos'),
  ('costos', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('costdec', 'Cost Management: A Strategic Emphasis (Blocher)'),
  ('costdec', 'Trabajo integrador en equipo'),
  ('costdec', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('contintl', 'Principales diferencias US GAAP-IFRS-NIF'),
  ('contintl', 'Exposición por equipo con casos prácticos'),
  ('instfin', 'NIF 2023-2024 (IMCP/CINIF)'),
  ('instfin', 'Especialistas invitados en valuación'),
  ('instfin', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('contraloria', 'Controllership (Rochl-Anderson)'),
  ('contraloria', 'Apuntes propios de clase'),
  ('imp1', 'LISR, RLISR, CFF y Resolución Miscelánea vigentes'),
  ('imp1', 'Ejemplos numéricos por tema'),
  ('imp1', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('imp2', 'LISR, LIVA y tratados fiscales vigentes'),
  ('imp2', 'Ejercicios por fase del curso'),
  ('imp2', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('impfis', 'LISR Título IV, LIVA y RMF vigentes'),
  ('impfis', 'Ejercicios numéricos por tema'),
  ('impfis', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('neg1', 'Próximamente'),
  ('tray1', 'Próximamente'),
  ('intro', 'Próximamente'),
  ('fin2', 'Próximamente'),
  ('integrada', 'Próximamente'),
  ('corporativa', 'Próximamente'),
  ('tray2', 'Próximamente'),
  ('tray3', 'Próximamente'),
  ('esg', 'Próximamente'),
  ('riesgos', 'Próximamente'),
  ('fiscalint', 'Próximamente'),
  ('ecogerencial', 'Próximamente'),
  ('calc', 'Temario oficial ITAM'),
  ('calc', 'Taller de cómputo quincenal'),
  ('calc', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('algebra', 'Temario oficial ITAM (MAT-12350)'),
  ('algebra', 'Solver de Excel para programación lineal'),
  ('algebra', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('est1', 'Temario oficial ITAM (EST-10101)'),
  ('est1', 'Lenguaje R para análisis exploratorio'),
  ('est1', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('est2', 'Temario oficial ITAM (EST-10102)'),
  ('est2', 'Lenguaje R para inferencia estadística'),
  ('est2', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('pronosticos', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('introderecho', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('derechocorp', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('derfiscal1', 'Apuntes propios ampliados (Jafet Vallejo)'),
  ('derlaboral', 'Apuntes propios ampliados (Jafet Vallejo)');

insert into public.quiz_questions (subject_id, question, options, correct_index) values
  ('proc', 'Un ajuste por depreciación acumulada afecta principalmente a:', '["Estado de resultados y balance","Solo el flujo de efectivo","Solo cuentas de orden","Ninguna cuenta patrimonial"]'::jsonb, 0),
  ('cp1', 'Bajo NIF, el marco conceptual establece que la información financiera debe ser:', '["Confidencial y subjetiva","Relevante y confiable","Solo relevante para el SAT","Opcional para PyMEs"]'::jsonb, 1),
  ('fin1', 'En Excel, para traer flujos futuros a valor presente sin incluir el periodo 0 dentro de la fórmula se usa:', '["VNA() sumando el año 0 fuera de la función","VNA() incluyendo el año 0 dentro","VF() directamente","PAGO() con tasa negativa"]'::jsonb, 0),
  ('cost', 'El punto de equilibrio en unidades se calcula como:', '["Costos fijos / (Precio - Costo variable unitario)","Costos variables / Precio","Ingresos totales / Costos totales","Utilidad / Precio"]'::jsonb, 0),
  ('aud', 'La evidencia de auditoría suficiente y adecuada se refiere principalmente a:', '["Cantidad y calidad de la evidencia","Solo la cantidad de documentos","Opinión personal del auditor","El tamaño de la empresa auditada"]'::jsonb, 0),
  ('anfin', 'El EBITDA se utiliza principalmente para analizar:', '["Las actividades de operación de la empresa","Solo el apalancamiento financiero","Únicamente la política de dividendos","El valor nominal de las acciones"]'::jsonb, 0),
  ('combneg', 'En una consolidación, el crédito mercantil surge cuando:', '["El precio pagado excede el valor razonable de los activos netos identificables","El valor en libros es mayor al precio pagado","No hay diferencia entre precio y valor contable","Se trata de una escisión, no de una adquisición"]'::jsonb, 0),
  ('costos', 'En un sistema de costos por procesos, las unidades equivalentes sirven para:', '["Prorratear el costo entre unidades terminadas y en proceso","Calcular exclusivamente el costo de la mano de obra","Sustituir el estado de resultados","Determinar el precio de venta final"]'::jsonb, 0),
  ('costdec', 'Bajo costeo absorbente, a diferencia del costeo directo, los gastos indirectos de fabricación fijos se:', '["Incluyen como parte del costo del producto","Excluyen siempre del costo del producto","Cargan directamente a capital contable","Eliminan del estado de resultados"]'::jsonb, 0),
  ('contintl', 'Bajo IFRS 15, el reconocimiento de ingresos se basa en un modelo de:', '["5 pasos centrados en la transferencia de control","Reconocimiento inmediato al firmar el contrato","Reconocimiento solo al cobrar en efectivo","3 pasos basados en la entrega física"]'::jsonb, 0),
  ('instfin', 'La NIF C-16 regula principalmente:', '["El deterioro de instrumentos financieros por cobrar","Los instrumentos financieros derivados","El capital contable","Los inventarios"]'::jsonb, 0),
  ('contraloria', 'La segregación de funciones como herramienta de control interno busca principalmente:', '["Evitar que una sola persona controle todo un proceso susceptible de fraude","Reducir el número de empleados","Aumentar la velocidad de los procesos","Eliminar la necesidad de auditorías"]'::jsonb, 0),
  ('imp1', 'Para que un gasto sea deducible para efectos de ISR, generalmente debe:', '["Cumplir los requisitos generales y específicos que marca la LISR","Solo estar registrado en la contabilidad","Ser aprobado verbalmente por el SAT","Superar cierto monto mínimo sin excepción"]'::jsonb, 0),
  ('impfis', 'Los ingresos por sueldos de una persona física están sujetos a:', '["Retención provisional por parte del patrón","Pago directo del trabajador sin retención","Exención total del ISR","Tasa fija del 10% sin importar el monto"]'::jsonb, 0),
  ('cost', 'Según la distinción entre costo y gasto en tus apuntes, el costo se diferencia del gasto en que:', '["El costo da la posibilidad de generar una ganancia futura, mientras el gasto no","El costo siempre es mayor en monto que el gasto","El gasto solo existe en empresas industriales","El costo nunca aparece en los estados financieros"]'::jsonb, 0),
  ('costos', 'Un factor de costo (cost driver) se define como:', '["Cualquier factor que cambia la cantidad del costo total","El precio de venta fijado por la empresa","El total de ingresos del periodo","La depreciación acumulada de un activo"]'::jsonb, 0),
  ('aud', 'El Código de Conducta Profesional (AICPA) distingue reglas aplicables a:', '["Miembros en la práctica pública y miembros en el mundo empresarial","Únicamente empresas que cotizan en bolsa","Solo auditores internos, nunca externos","Exclusivamente estudiantes en formación"]'::jsonb, 0),
  ('combneg', 'Bajo el método de la participación para inversiones con influencia significativa, el inversionista reconoce:', '["Su porción proporcional de las utilidades de la participada","El 100% de las utilidades de la participada","Solo los dividendos recibidos en efectivo","Ninguna utilidad hasta vender la inversión"]'::jsonb, 0),
  ('cp1', 'Las razones de solvencia de una empresa miden principalmente:', '["Su capacidad de cumplir obligaciones a largo plazo","Su rentabilidad sobre ventas","El nivel óptimo de inventarios","El tipo de cambio aplicable a sus operaciones"]'::jsonb, 0),
  ('cp2', 'En un plan de pensiones de contribución (aportación) definida, el riesgo de la inversión lo asume principalmente:', '["El empleado","La empresa patrocinadora","El gobierno","El auditor externo"]'::jsonb, 0),
  ('imp1', 'Bajo el principio de renta mundial aplicable a residentes en México, el ISR grava:', '["Todos los ingresos, sin importar la ubicación de la fuente de riqueza","Solo los ingresos de fuente nacional","Solo ingresos superiores a cierto monto anual","Únicamente ingresos cobrados en efectivo"]'::jsonb, 0),
  ('imp2', 'El saldo de la CUFIN (Cuenta de Utilidad Fiscal Neta) indica principalmente:', '["Hasta qué monto se pueden pagar dividendos sin generar ISR adicional","El monto máximo de dividendos que legalmente se puede repartir","El capital social de la empresa","La utilidad contable del ejercicio"]'::jsonb, 0),
  ('instfin', 'Bajo IFRS 9, la Estimación para Pérdidas Crediticias Esperadas (ECL) se reconoce considerando:', '["12 meses o toda la vida del instrumento, según el grado de deterioro","Únicamente pérdidas ya realizadas y cobradas","Solo el valor nominal del instrumento","Un porcentaje fijo del 5% en todos los casos"]'::jsonb, 0),
  ('anfin', 'El análisis vertical de un estado financiero se caracteriza por ser:', '["Estático: analiza un solo periodo respecto a una cifra base (100%)","Dinámico: compara varios periodos entre sí","Exclusivo para auditores externos","Aplicable solo al estado de flujo de efectivo"]'::jsonb, 0),
  ('calc', 'En el método de Lagrange, la optimización con restricciones se usa para:', '["Maximizar o minimizar una función sujeta a una o más restricciones","Calcular derivadas parciales sin ninguna restricción","Resolver únicamente sistemas homogéneos","Encontrar la matriz inversa de una función"]'::jsonb, 0),
  ('algebra', 'El objetivo de la eliminación Gaussiana es llevar la matriz a su forma:', '["Escalonada reducida","Diagonal únicamente, sin importar el resto","Transpuesta","Triangular inferior exclusivamente"]'::jsonb, 0),
  ('est1', 'El Teorema de Bayes permite calcular:', '["Probabilidades condicionales a partir de probabilidades conocidas","Únicamente la media de una distribución","La varianza de una muestra aleatoria","El coeficiente de correlación de Pearson"]'::jsonb, 0),
  ('est2', 'El Teorema Central del Límite establece que, para muestras suficientemente grandes:', '["La distribución muestral de la media se aproxima a una normal","La varianza poblacional siempre es cero","Los datos dejan de ser aleatorios","Solo aplica si la muestra es menor a 30"]'::jsonb, 0),
  ('introderecho', 'La capacidad de goce, a diferencia de la capacidad de ejercicio, se adquiere:', '["Al nacer","Al cumplir la mayoría de edad","Al contraer matrimonio","Al obtener un título profesional"]'::jsonb, 0),
  ('derechocorp', 'En caso de quiebra de un banco en México, el IPAB paga a cada ahorrador hasta:', '["400,000 UDIS","25,000 UDIS","Sin límite alguno","10,000 UDIS"]'::jsonb, 0),
  ('derfiscal1', 'Cuando el gasto público del Estado es mayor a sus ingresos, se genera un:', '["Déficit presupuestario","Superávit presupuestario","Balance presupuestario","Ingreso petrolero"]'::jsonb, 0),
  ('derlaboral', 'El derecho al trabajo en México tiene su origen constitucional principalmente en:', '["El Artículo 123 de la CPEUM","El Artículo 27 de la CPEUM","El Código de Comercio","La Ley del Seguro Social"]'::jsonb, 0),
  ('fin1', 'Bajo el criterio del Valor Presente Neto (VPN), un proyecto de inversión debe aceptarse cuando:', '["El VPN es positivo","El VPN es negativo","La TIR es menor a la tasa de descuento","El periodo de recuperación es infinito"]'::jsonb, 0),
  ('fin1', 'El Costo Promedio Ponderado de Capital (CPPC / WACC) combina:', '["El costo de la deuda y el costo del capital accionario, ponderados por su peso en la estructura de capital","Únicamente el costo de la deuda","Únicamente el costo del capital accionario","Solo la tasa libre de riesgo"]'::jsonb, 0),
  ('fin1', 'En el Modelo de Dividendos Descontados con crecimiento constante, el precio de una acción depende de:', '["El dividendo esperado, la tasa de descuento y la tasa de crecimiento","Únicamente el valor nominal de la acción","El precio de cierre del día anterior","El volumen de acciones en circulación"]'::jsonb, 0),
  ('pronosticos', 'El método Delphi se caracteriza por:', '["Reunir expertos anónimos que responden cuestionarios en rondas iterativas hasta llegar a consenso","Juntar a los expertos en una sala para debatir abiertamente","Encuestar únicamente a consumidores no expertos","Usar solo datos históricos, sin juicio humano"]'::jsonb, 0),
  ('pronosticos', 'Un pronóstico basado en series de tiempo se caracteriza por:', '["Usar el comportamiento histórico de la propia variable, sin importar qué lo causa","Usar exclusivamente variables explicativas externas","Requerir siempre datos transversales, nunca longitudinales","Aplicarse solo a mercados nuevos sin historia"]'::jsonb, 0),
  ('pronosticos', 'La multicolinealidad perfecta en un modelo de regresión ocurre cuando:', '["Las variables explicativas están perfectamente correlacionadas entre sí","Los residuos tienen varianza constante","La media de los residuos es igual a cero","El modelo tiene un R² de exactamente 1"]'::jsonb, 0),
  ('pronosticos', 'Para identificar qué parte de la variación en una serie de tiempo se debe a la estacionalidad, el primer paso es:', '["Desestacionalizar la serie y comparar contra la serie real","Calcular la TIR de la serie","Aplicar el método Delphi","Eliminar todos los datos atípicos"]'::jsonb, 0);

insert into public.news (tag, title, published_on) values
  ('NIF', 'Actualizaciones periódicas al marco de Normas de Información Financiera en México', '2026-01-01'::date),
  ('SAT', 'Cambios recurrentes en obligaciones fiscales y comprobación electrónica (CFDI)', '2026-01-01'::date),
  ('IFRS', 'Convergencia internacional entre NIF mexicanas y estándares IFRS', '2026-01-01'::date),
  ('Auditoría', 'Mayor énfasis en auditoría de sostenibilidad y reportes ESG', '2026-01-01'::date),
  ('Tecnología', 'Adopción de automatización e IA en procesos contables y de cierre', '2026-01-01'::date);
